#!/bin/sh /etc/rc.common

START=90
STOP=15

start() {
	config_load lingti
	local enable
	config_get_bool enable lingti enabled
	if [ "$enable" -eq 0 ]; then
	  stop
	else
	  /usr/bin/lingti/lingti >/dev/null 2>&1 &
	fi
}

stop() {
	config_load lingti
	local enabled
	config_get_bool enabled lingti enabled
	kill -9 `pgrep -f "/var/bin/lingti"` 2>/dev/null
}
